en:
  dashboard:
    welcome_html: |
      <div style="position:relative;">
        %{logo_img_tag}
        <a href="https://tinyurl.com/cheahaAL" target="_blank">
          <div style="float:left;position:absolute;display:block;left:245px;top:-6px;padding:10px 20px;"> </div>
        </a>
      </div>
      <p class="lead">OnDemand provides an integrated, single access point for all of your HPC resources.</p>
    motd_title: "Message of the Day"
